name: CI

on: [push]

jobs:
  Run_Tests:

    runs-on: ubuntu-latest

    steps:
    - name: Test docker-compose
      run: docker-compose build
    
    - name: Run python server API
      run: cd cityAPI
           - pip3 install -r requirements.txt
           - python3 app.py &


    - name: Test docker-compose
      run: curl localhost:5000/graphs/roads
