name: CI

on: [push]

jobs:
  Run_Tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Test docker-compose
      run: docker-compose build
    
    - uses: actions/checkout@v1
    - name: Run python server API
      run: cd cityAPI && pip3 install -r requirements.txt && python3 app.py &


    - uses: actions/checkout@v1
    - name: Test docker-compose
      run: curl localhost:5000/graphs/roads
