name: CI

on: [push]

jobs:
  Run_Tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Test docker-compose
      run: docker-compose build
    
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: 3.x
        architecture: x64
    
    - name: Launch API server
      run: |
          cd cityAPI
          pip install -r requirements.txt
          python server.py &
          echo "::set-env name=PID_SERVER::$!"
          

    - name: Test API
      run: curl localhost:5000/graphs/roads

    - name: Environment Printer
      uses: managedkaos/print-env@v1.0
  
    - name: Kill server API
      run: kill $PID_SERVER
